baseURL: "https://tech.tf1.fr/"
languageCode: "fr-FR"
title: "Blog technique e-TF1"
theme: "hugo-theme-novela-mytf1"
pygmentsstyle: "monokai"
paginate: 6
social:
  linkedin: "https://www.linkedin.com/company/e-tf1/"
  github: "https://github.com/etf1"
  feed: "https://tech.tf1.fr/index.xml"
markup:
   defaultMarkdownHandler: blackFriday
   blackFriday:
     hrefTargetBlank: 1
enableRobotsTXT: true
params:
  description: "Découvrez les coulisses de MYTF1, la plateforme de streaming vidéo de TF1"
  seo:
    default_image: "/images/mytf1.png"
    locale: "fr_FR"
    keywords: "mytf1, tf1, streaming, player, video, go, golang, react, js, javascript, css, android, ios, kotlin, swift, nginx, drm, widevine, elemental, aws, mongodb, kafka"