baseURL: "/"
languageCode: "fr-FR"
title: "Blog technique eTF1"
theme: "hugo-theme-novela-mytf1"
pygmentsstyle: "monokai"
paginate: 6
social:
  linkedin: "https://www.linkedin.com/company/e-tf1/"
  github: "https://github.com/etf1"
